### ISSUE TITLE
`ignores` Property Not Fully Excluding Files from Linting

### ISSUE THREAD

**Issue by arpowers** [antfu/eslint-config#342] opened 2023-11-30 18:43 UTC
### Describe the bug

**Configuration:**
```json
"ignores": [
  "**/.ref/**"
]
```

**Problem:**
Files in `.ref` are not fully ignored by the linter; they are linted without applying my rule overrides.

**Question:**
Is this a bug, or how can I fully exclude files from linting? Maybe some clarification is needed

Thanks!

### Reproduction

not needed (docs based)

### System Info

```Shell
Mac / Node
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-12-01 23:02
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-12-01 23:02 UTC

**Comment by husayt** [comment] 2023-12-21 22:45
I set markdown to false
```
    formatters: {
        markdown: false
    },
```
and still get makrdown files processed
