### ISSUE TITLE
inheritAttrs issue on typescript setup

### ISSUE THREAD

**Issue by dolbex** [antfu/eslint-config#174] opened 2023-04-18 11:29 UTC
### Describe the bug

I'm not sure if this is a bug but certainly probably not what is intended. If you have a typescript composition component you can run into this situation:

```
<script lang="ts">
  // use normal <script> to declare options
  export default {
    inheritAttrs: false,
  }
</script>

<script setup lang="ts">
.....
```

That will screw up and pull the `export default` into the script setup area.

### Reproduction

NA - given above

### System Info

```Shell
NA
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sadeghbarati** [comment] 2023-04-18 12:34
#81

**Comment by antfu** [comment] 2023-10-09 07:23
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-10-09 07:23 UTC
