### ISSUE TITLE
bug: no error when attribute can `undefined` because `arg?: <type>`

### ISSUE THREAD

**Issue by tachibana-shin** [antfu/eslint-config#99] opened 2022-05-30 00:49 UTC
Hi antfu!,

I'm using your eslint configuration and it has a very serious error for me.
It appears that this configuration has disabled the ability to recognize a value that could be `undefined` when it is defined with `?:`

Not working:
![image](https://user-images.githubusercontent.com/45375496/170898601-eb3d139a-1fa7-4ea5-8c62-5e404a911079.png)

Working:
![image](https://user-images.githubusercontent.com/45375496/170898621-f0c9ccd6-8908-4983-a596-66a2db2e85e9.png)

You can see that when I specify `format?:  string[]` then eslint does not specify `format` as undefined and `format.forEach` is still valid. But when I specify the ` format?: string[] | void`, the format.forEach will experience an error.

Please fix,
Thanks for read!

**Comment by antfu** [comment] 2022-05-30 04:46
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-05-30 04:46 UTC
