### ISSUE TITLE
Does not run on save

### ISSUE THREAD

**Issue by safejace** [antfu/eslint-config#354] opened 2023-12-08 17:26 UTC
### Describe the bug

when i save my files in vscode, it does not format the files

### Reproduction

https://stackblitz.com/edit/github-nwnyxj?file=server%2Fapi%2Ftest.ts

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 4.20 GB / 31.01 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.10.0 - ~/.local/share/pnpm/node
    npm: 10.2.3 - ~/.local/share/pnpm/npm
    pnpm: 8.7.6 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.71
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

edit:

just a note cuz i was messing around with it. but i added the formatters to the repro and got this error:

`Error: Unexpected key "formatters" found.`

**Comment by Dimava** [comment] 2023-12-08 17:40
Does it work if you save multiple times?

**Comment by safejace** [comment] 2023-12-08 17:44
> Does it work if you save multiple times?

no. does it for you in the repro?

**Comment by antfu** [comment] 2023-12-09 02:40
The reproduction works for me on my local VS Code. Did you even get https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint installed?

**Comment by safejace** [comment] 2023-12-11 16:40
> The reproduction works for me on my local VS Code. Did you even get https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint installed?

yes, as far as i am aware, i had everything installed as per the readme.

why are the files not being formatted in the repro env?

**Comment by kissu** [comment] 2023-12-14 22:56
Do you see something in your ESlint tab? An error that could be helpful?
![image](https://github.com/antfu/eslint-config/assets/5133074/28ab9b8e-d50b-4cd2-8b57-4d81b3f444f8)

**Comment by antfu** [comment] 2023-12-15 19:21
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-12-15 19:21 UTC

**Comment by lucacicada** [comment] 2023-12-17 11:43
I really do not want to reopen this, but I think I can provide some help as I had very similar problem.

I forgot to install `typescript` and as such, eslint did ignore all `*.ts` files.

If you just run `eslint .` you will end up with an empty log with no problems cause it skips all auto-ignored files, so instead, pin just a single file down.

To diagnose the problem, break a file intentionally then run:

```bash
pnpm eslint src/index.ts --debug
```

![image](https://github.com/antfu/eslint-config/assets/100947658/c3918a2a-bca1-4a83-b218-94014afe41fb)

So yhea basically, (future me) install `typescript`, plus it might be worth it to run eslint on a single file.
