### ISSUE TITLE
"lint": "eslint ."

### ISSUE THREAD

**Issue by Lazy-Hand** [antfu/eslint-config#484] opened 2024-05-22 05:51 UTC
### Describe the bug

ConfigError: Config "antfu/javascript/rules": Key "rules": Key "accessor-pairs": structuredClone is not defined

### Reproduction

"lint": "eslint ."

### System Info

```Shell
win
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment] 2024-05-22 06:05
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2024-05-22 06:05 UTC
