### ISSUE TITLE
ENOENT: no such file or directory, open '.gitignore'

### ISSUE THREAD

**Issue by hairyf** [antfu/eslint-config#328] opened 2023-11-20 07:13 UTC
### Describe the bug

I encountered an error using this configuration by creating a vite react project(vscode eslint console)

![image](https://github.com/antfu/eslint-config/assets/49724027/d3a5bdde-049f-4456-a043-e147789e6c30)

### Reproduction

The following link cannot be reproduced because it is an error in vsocde eslint plugin

### System Info

```Shell
System:
    OS: Windows 11 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 4.72 GB / 15.93 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-11-20 11:27
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2023-11-20 11:27 UTC
