### ISSUE TITLE
Failed to load plugin 'vue' declared in '.eslintrc » @antfu/eslint-config » @antfu/eslint-config-vue': Cannot find module 'eslint-plugin-vue'

### ISSUE THREAD

**Issue by laterdayi** [antfu/eslint-config#238] opened 2023-09-03 11:51 UTC
### Describe the bug

[Info  - 19:50:36] ESLint server is starting.
[Info  - 19:50:36] ESLint server running in node v16.17.1
[Info  - 19:50:36] ESLint server is running.
[Info  - 19:50:37] ESLint library loaded from: \node_modules\.pnpm\eslint@8.48.0\node_modules\eslint\lib\api.js
Uncaught exception received.
Error: Failed to load plugin 'vue' declared in '.eslintrc » @antfu/eslint-config » @antfu/eslint-config-vue': Cannot find module 'eslint-plugin-vue'
Require stack:
- F:\my\stp-web\__placeholder__.js
Referenced from:\node_modules\.pnpm\@antfu+eslint-config-vue@0.41.0_@typescript-eslint+eslint-plugin@6.5.0_@typescript-eslint+par_2ms6xhs7zi2fynkulihv6wqgdm\node_modules\@antfu\eslint-config-vue\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)

### Reproduction

*

### System Info

```Shell
window
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-09-03 13:12
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-09-03 13:12 UTC
