### ISSUE TITLE
vscode-eslint无法启用

### ISSUE THREAD

**Issue by light-huangli** [antfu/eslint-config#348] opened 2023-12-04 01:43 UTC
### Describe the bug

采用npx @antfu/eslint-config@latest，在eslint-vscode2.42中
[Error - 09:25:03] Error: Invalid Options:
- Unknown options: extensions
- 'extensions' has been removed.
    at processOptions (D:\workspace\hk-uni-vite-ts-template\node_modules\eslint\lib\eslint\eslint-helpers.js:789:15)
    at new FlatESLint (D:\workspace\hk-uni-vite-ts-template\node_modules\eslint\lib\eslint\flat-eslint.js:559:34)
    at q (c:\Users\lightli\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:18735)
    at E (c:\Users\lightli\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:19173)
    at e.validate (c:\Users\lightli\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:24819)
    at c:\Users\lightli\.vscode\extensions\dbaeumer.vscode-eslint-2.4.2\server\out\eslintServer.js:1:221494
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Reproduction

- Unknown options: extensions - 'extensions' has been removed.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 3.85 GB / 15.83 GB
  Binaries:
    Node: 18.0.0 - D:\Program Files\node\node.EXE
    Yarn: 1.22.21 - D:\Program Files\node\node_cache\yarn.CMD
    npm: 9.7.2 - D:\Program Files\node\npm.CMD
    pnpm: 8.2.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-12-04 09:44
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2023-12-04 09:44 UTC

**Comment by alexrodriguezjob** [comment] 2024-01-31 20:41
I was having the same issue and was related to an option in `.vscode/settings.json`:

```
  "eslint.options": {
    "extensions": [
      ".ts",
      ".js",
      ".vue"
    ]
  },
  ```

I removed it and the error disappeared.
