### ISSUE TITLE
bug: asyncArrow can't be fixed

### ISSUE THREAD

**Issue by Simon-He95** [antfu/eslint-config#101] opened 2022-06-05 04:26 UTC
![1654402571144](https://user-images.githubusercontent.com/57086651/172034993-08620fc7-317c-43ae-9824-b3195cb366c7.png)

when i use eslint to fix in main package, the subpackage error can't be fixed.
I try to remove `extends:"@antfu"`, fix worked.

Additionally, the same code in main package is not considered an error.

`const a = async () => {
  return 1
}
a()` both in main and sub package (vitest module),the error just occur in sub package

**Comment by antfu** [comment] 2022-06-05 13:21
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-05 13:21 UTC
