### ISSUE TITLE
Linter rules seem to not work with Vue 2.x projects

### ISSUE THREAD

**Issue by spend-cloud-tom** [antfu/eslint-config#367] opened 2023-12-18 13:33 UTC
### Describe the bug

I'm running the config @ 2.3.x on a project using vue@2.7.15, this runs fine. Whenever I update the config to 2.4.x I'm getting these errors, which I believe have to do with a template parser mismatch.

```
[...]/src/pages/x.vue
  0:0  error  Preprocessing error: Cannot read properties of undefined (reading 'styles')`
```

This is my config:

```
const antfu = require('@antfu/eslint-config').default

module.exports = antfu(
  {
    vue: true,
    vueVersion: 2,
    typescript: false,
    css: true,
  },
  {
    ignores: [
      'docker-compose.dev.yml',
      'src/init/pendo.js',
      'src/main-test.js',
      'src/utils/pin.js',
    ],
  },
  {
    files: ['**/*'],
    rules: {
      'node/prefer-global/process': 'off',
    },
  },
  {
    files: ['tasks/**/*'],
    rules: {
      'no-console': 'off',
    },
  },
  {
    files: ['src/**/*.spec.js', 'src/test-utils/**/*', '**/stub*.js', '**/__mocks__/**/*'],
    languageOptions: {
      globals: {
        afterAll: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        describe: 'readonly',
        expect: 'readonly',
        it: 'readonly',
        jest: 'readonly',
        test: 'readonly',
      },
    },
  },
  {
    files: ['**/*.vue'],
    rules: {
      'vue/component-definition-name-casing': ['error', 'kebab-case'],
      'vue/component-name-in-template-casing': ['error', 'kebab-case'],
      'vue/custom-event-name-casing': ['error', 'kebab-case', { ignores: [] }],
      'vue/no-deprecated-events-api': 'off',
      'vue/no-deprecated-router-link-tag-prop': 'off',
      'vue/no-deprecated-v-bind-sync': 'off',
      'vue/no-deprecated-v-on-native-modifier': 'off',
      'vue/no-unused-refs': 'off',
      'vue/no-v-for-template-key-on-child': 'off',
      'vue/require-explicit-emits': 'off',
      'vue/v-on-event-hyphenation': 'off',
      'vue/no-deprecated-dollar-scopedslots-api': 'off',
    },
  },
  {
    files: ['sc-overview-filter-field.vue'],
    rules: {
      '@typescript-eslint/no-invalid-this': 'off',
    },
  },
  {
    files: ['src/__mocks__/**/*'],
    rules: {
      'no-useless-call': 'off',
      'import/export': 'off',
    },
  },
  {
    files: ['src/utils/**/*'],
    rules: {
      'eslint-comments/no-unlimited-disable': 'off',
    },
  },
  {
    files: ['src/test-utils/**/*'],
    rules: {
      'no-useless-call': 'off',
      'import/export': 'off',
    },
  },
  {
    files: ['tests/e2e/**/*'],
    rules: {
      'padding-line-between-statements': 'off',
    },
  },
  {
    files: ['src/pages/application-management/organization/structure.vue'],
    rules: {
      'no-invalid-this': 'off',
    },
  },
)
```

### Reproduction

Use linter config 2.4.x on a vue 2 project

### System Info

```Shell
Node v20.10.0, Ubuntu 22.04, vue 2.17.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-12-19 22:56
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-12-19 22:56 UTC

**Comment by usercao** [comment] 2024-01-08 08:14
![image](https://github.com/antfu/eslint-config/assets/13760476/edf7f559-c561-4898-beb7-6e86a57418a6)
```js
export default antfu(
  {
    vueVersion: 2,
  },
)
```
There is indeed this issue, please lock the `2.3.4` version.

**Comment by whitexie** [comment] 2024-01-24 10:09
我这边也出现了这个问题，好像是`eslint-processor-vue-blocks` 引起的  

vscode 日志: 
```log
2024-01-24T10:08:11.658Z eslint:flat-eslint Searching for eslint.config.js
2024-01-24T10:08:11.658Z eslint:flat-eslint Loading config from /Users/xxxxx/temp/eslint-issues-367/eslint.config.js
2024-01-24T10:08:11.658Z eslint:flat-eslint Config file URL is file:///Users/xxxxx/temp/eslint-issues-367/eslint.config.js
2024-01-24T10:08:11.718Z eslint:flat-eslint Lint /Users/xxxxx/temp/eslint-issues-367/src/components/TheWelcome.vue
2024-01-24T10:08:11.718Z eslint:linter Linting code for /Users/xxxxx/temp/eslint-issues-367/src/components/TheWelcome.vue (pass 1)
2024-01-24T10:08:11.718Z eslint:linter Verify
2024-01-24T10:08:11.718Z eslint:linter With flat config: /Users/xxxxx/temp/eslint-issues-367/src/components/TheWelcome.vue
2024-01-24T10:08:11.718Z eslint:linter Apply the processor: { meta: { name: 'merged-processor:eslint-plugin-vue+eslint-processor-vue-blocks' }, supportsAutofix: true, preprocess: [Function: preprocess], postprocess: [Function: postprocess] }
2024-01-24T10:08:11.718Z eslint:linter Preprocessing error: Cannot read properties of undefined (reading 'styles')
TypeError: Cannot read properties of undefined (reading 'styles')
    at Object.preprocess (file:///Users/xxxxx/temp/eslint-issues-367/node_modules/.pnpm/eslint-processor-vue-blocks@0.1.1_eslint@8.56.0/node_modules/eslint-processor-vue-blocks/dist/index.mjs:73:20)
    at /Users/xxxxx/temp/eslint-issues-367/node_modules/.pnpm/eslint-merge-processors@0.1.0_eslint@8.56.0/node_modules/eslint-merge-processors/dist/index.cjs:14:46
    at Array.flatMap (<anonymous>)
    at preprocess (/Users/xxxxx/temp/eslint-issues-367/node_modules/.pnpm/eslint-merge-processors@0.1.0_eslint@8.56.0/node_modules/eslint-merge-processors/dist/index.cjs:13:25)
    at Linter._verifyWithFlatConfigArrayAndProcessor (/Users/xxxxx/temp/eslint-issues-367/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:1479:22)
    at Linter._verifyWithFlatConfigArray (/Users/xxxxx/temp/eslint-issues-367/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:1848:25)
    at Linter.verify (/Users/xxxxx/temp/eslint-issues-367/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:1433:65)
    at Linter.verifyAndFix (/Users/xxxxx/temp/eslint-issues-367/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/linter/linter.js:2068:29)
    at verifyText (/Users/xxxxx/temp/eslint-issues-367/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/eslint/flat-eslint.js:474:48)
    at FlatESLint.lintText (/Users/xxxxx/temp/eslint-issues-367/node_modules/.pnpm/eslint@8.56.0/node_modules/eslint/lib/eslint/flat-eslint.js:957:26)
2024-01-24T10:08:11.719Z eslint:linter Generating fixed text for /Users/xxxxx/temp/eslint-issues-367/src/components/TheWelcome.vue (pass 1)
2024-01-24T10:08:11.719Z eslint:source-code-fixer Applying fixes
2024-01-24T10:08:11.719Z eslint:source-code-fixer shouldFix parameter was false, not attempting fixes
2024-01-24T10:08:11.719Z eslint:flat-eslint Linting complete in: 60ms

```

**Comment by usercao** [comment] 2024-01-24 10:30
@antfu @whitexie It's useless if you set it like this, the settings in `formatters` still won't take effect.
```js
{
    vue: {
      vueVersion: 2,
      sfcBlocks: false,
    },
    formatters: {
      css: true, // Not effective
      html: true, // Not effective
      markdown: 'prettier', // Not effective
    }, 
}
```

**Comment by whitexie** [comment] 2024-01-24 10:58
@antfu   `eslint-processor-vue-blocks` 对于`@vue/compiler-sfc` 的依赖版本是3.3以上， 但是本地引用的是`@vue/compiler-sfc@2.7.16`版本。
<img width="1176" alt="image" src="https://github.com/antfu/eslint-config/assets/30469146/52497486-f3eb-4209-97a6-f477c97baa1e">

**Comment by usercao** [comment] 2024-01-25 09:03
@whitexie Installing `eslint-plugin-format` does not work.

**Comment by whitexie** [comment] 2024-01-26 01:27
@usercao 如果是`.vue`中的style，需要将`sfcBlocks` 设置为`true`；
但`eslint-processor-vue-blocks` 依赖`@vue/compiler-sfc`的3.3以上版本；

我从`yarn`迁移到`pnpm`之后，`pnpm`可以解决这个依赖冲突的问题。

删除`node_modules`，
在项目根路径下创建`.npmrc`, 写入： 
```
auto-install-peers=true
```
重新安装依赖就可以了。

**Comment by usercao** [comment] 2024-01-26 01:29
@whitexie Is there any solution to using `yarn`?

**Comment by whitexie** [comment] 2024-01-26 01:41
不知道哈，没找到相关解决办法。

**Comment by usercao** [comment] 2024-01-26 01:43
@whitexie 👌thanks

**Comment by romansp** [comment] 2024-03-05 21:14
This configuration seem to help to ignore `style` block.

```js
sfcBlocks: {
  blocks: {
    styles: false,
  },
},
```

**Comment by LOUSANPANG** [comment] 2024-07-03 09:51
> @whitexie Is there any solution to using `yarn`?

It seems to be solved with PNPM

**Comment by sonofmagic** [comment] 2024-08-13 09:28
Here I give a `yarn` solution. In `package.json` , add:
```json
  "resolutions": {
    "**/eslint-processor-vue-blocks/@vue/compiler-sfc": "^3.3.0"
  }
```
Then the problem is solved
