### ISSUE TITLE
Unable to use with eslint 9.0.0

### ISSUE THREAD

**Issue by dogmatic69** [antfu/eslint-config#442] opened 2024-04-09 10:45 UTC
### Describe the bug

On a fresh docker image using `node:alpine` I am unable to import the lib.

```
# yarn add eslint
....
# yarn add @antfu/eslint-config
...

# node 
Welcome to Node.js v21.7.1.
Type ".help" for more information.
> const { default: antfu } = await import("@antfu/eslint-config");
Uncaught:
Error: This method cannot be used with flat config. Add your entries directly into the config array.
    at assertEslintrcConfig (/node_modules/eslint/lib/linter/linter.js:1286:15)
    at Linter.getRules (/node_modules/eslint/lib/linter/linter.js:2215:9)
    at Object.<anonymous> (/node_modules/eslint-plugin-unused-imports/lib/rules/load-rule.js:10:32)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)


# cat package.json 
{
  "dependencies": {
    "@antfu/eslint-config": "^2.13.0",
    "eslint": "^9.0.0"
  }
}

```

### Reproduction

in the description

### System Info

```Shell
System:
    OS: Linux 6.5 Alpine Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1.95 GB / 15.42 GB
    Container: Yes
    Shell: 1.36.1 - /bin/ash
  Binaries:
    Node: 21.7.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-04-09 11:19
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-09 11:19 UTC

**Comment by dogmatic69** [comment] 2024-04-09 12:05
Not sure you can get any more minimal that a clean node docker image and installing just eslint and this package. I provided the exact steps. What more you need?

**Comment by dogmatic69** [comment] 2024-04-09 12:12
Ok, even less now. Single command.

```
docker run --rm -it --entrypoint sh node:alpine -c "yarn add eslint; yarn add @antfu/eslint-config; node -e 'const { default: foo } = require(\"@antfu/eslint-config\")'"
```

**Comment by dogmatic69** [comment] 2024-04-09 12:19
Seems the issue is running with yarn.

```
$ docker run --rm -it --entrypoint sh --workdir /tmp node:alpine -c "npm install eslint @antfu/eslint-config; node -e 'const { default: foo } = require(\"@antfu/eslint-config\"); console.log(foo);'"

added 338 packages in 31s
...
[Function: antfu]
```

**Comment by antfu** [comment] 2024-04-09 12:20
I don't use docker, if the issue is not reproduce outside of docker, it might be be our issue

**Comment by dogmatic69** [comment] 2024-04-09 12:27
A docker image is the cleanest reproduction with no other things interfering. 

It is exactly the same error on my linux laptop and desktop. 

```
$ node -e 'const { default: foo } = require("@antfu/eslint-config")'
/tmp/foo/node_modules/eslint/lib/linter/linter.js:1286
        throw new Error("This method cannot be used with flat config. Add your entries directly into the config array.");
        ^

Error: This method cannot be used with flat config. Add your entries directly into the config array.
    at assertEslintrcConfig (/tmp/foo/node_modules/eslint/lib/linter/linter.js:1286:15)
    at Linter.getRules (/tmp/foo/node_modules/eslint/lib/linter/linter.js:2215:9)
    at Object.<anonymous> (/tmp/foo/node_modules/eslint-plugin-unused-imports/lib/rules/load-rule.js:10:32)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/tmp/foo/node_modules/eslint-plugin-unused-imports/lib/rules/no-unused-vars.js:11:14)

Node.js v18.13.0
```

**Comment by dogmatic69** [comment] 2024-04-09 12:32
![image](https://github.com/antfu/eslint-config/assets/94674/c3be522a-fc18-447f-886e-63377653477c)

Reproduced in a clean google cloud shell.

**Comment by LOUSANPANG** [comment] 2024-07-03 09:39
> > Reproduced with github [actions](https://github.com/dogmatic69/broken/actions/runs/8615800400/workflow#L1-L11).用 github actions 转载。
> > https://github.com/dogmatic69/broken/actions/runs/8615800400/job/23612082842#step:2:26
> 
> I seem to have this problem too. It seems to be caused by upgrading to eslint9. Downgrading eslint should solve it.

Hello, I ca n’t find the configuration document after the downgrade. Have you ever encountered it?

**Comment by Simon-He95** [comment] 2024-07-03 09:50
> > > Reproduced with github [actions](https://github.com/dogmatic69/broken/actions/runs/8615800400/workflow#L1-L11).用 github actions 转载。用 github actions 转载。
> > > https://github.com/dogmatic69/broken/actions/runs/8615800400/job/23612082842#step:2:26
> > 
> > 
> > I seem to have this problem too. It seems to be caused by upgrading to eslint9. Downgrading eslint should solve it.我似乎也有这个问题。这似乎是由升级到 eslint9 引起的。降级 eslint 应该可以解决这个问题。
> 
> Hello, I ca n’t find the configuration document after the downgrade. Have you ever encountered it?您好，降级后我找不到配置文档。你遇到过吗？

The error is because my local node version is too low. I can continue to use the latest eslint
