### ISSUE TITLE
Configuration for rule "import/newline-after-import" is invalid

### ISSUE THREAD

**Issue by creazy231** [antfu/eslint-config#212] opened 2023-07-04 10:58 UTC
### Describe the bug

I just started a fresh TypeScript project and I'm getting the error mentioned in the title.

Full error:
```
@antfu/eslint-config » @antfu/eslint-config-vue » @antfu/eslint-config-ts » @antfu/eslint-config-basic:
	Configuration for rule "import/newline-after-import" is invalid:
	Value {"count":1,"considerComments":true} should NOT have additional properties.
```

### Reproduction

Not possible on StackBlitz or CodeSandbox afaik

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 984.42 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Brave Browser: 114.1.52.129
    Chrome: 114.0.5735.198
    Safari: 16.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ayoub-elmendoub** [comment] 2023-07-06 17:20
I had similar errors, so i upgraded eslint to 8.44.0 & @antfu/eslint-config to 0.39.5
but I got this error
```
Error: .eslintrc.cjs » @antfu/eslint-config » @antfu/eslint-config-vue:
	Configuration for rule "vue/define-macros-order" is invalid:
	Value "defineOptions" should be equal to one of the allowed values
```
Call stack:
```
 at /home/omma/Documents/Github/ph-ui-next/node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2094:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/home/omma/Documents/Github/ph-ui-next/node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2091:34)
    at ConfigValidator.validateConfigArray (/home/omma/Documents/Github/ph-ui-next/node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2217:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/home/omma/Documents/Github/ph-ui-next/node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3974:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/home/omma/Documents/Github/ph-ui-next/node_modules/.pnpm/@eslint+eslintrc@2.1.0/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3780:21)
    at CLIEngine.getConfigForFile (/home/omma/Documents/Github/ph-ui-next/node_modules/.pnpm/eslint@8.44.0/node_modules/eslint/lib/cli-engine/cli-engine.js:980:14)
    at ESLint.calculateConfigForFile (/home/omma/Documents/Github/ph-ui-next/node_modules/.pnpm/eslint@8.44.0/node_modules/eslint/lib/eslint/eslint.js:667:26)
    at /home/omma/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js:1:22644
```

**Comment by antfu** [comment] 2023-07-08 11:37
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-07-08 11:37 UTC
