### ISSUE TITLE
Issue with style/brace-style rule

### ISSUE THREAD

**Issue by altrusl** [antfu/eslint-config#322] opened 2023-11-16 15:54 UTC
### Describe the bug

This is my config:

```js
import antfu from '@antfu/eslint-config'

export default antfu({
  rules: {
    'ts/brace-style': ['error', '1tbs', { allowSingleLine: true }],
  },
  stylistic: {
    'style/brace-style': ['error', '1tbs', { allowSingleLine: true }],
  },
})
```

Package.json
```json
  "devDependencies": {
    "@antfu/eslint-config": "^1.1.3",
    "@types/node": "^20.9.0",
    "@vitejs/plugin-vue": "^4.5.0",
    "eslint": "^8.53.0",
    "sass": "^1.69.5",
    "typescript": "^5.2.2",
    "vite": "^5.0.0"
  }
```

.vscode/settings.json

```json
  "eslint.experimental.useFlatConfig": true,
  "prettier.enable": false,
  "editor.formatOnSave": false,
  // Auto fix
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": "explicit",
    "source.organizeImports": "never"
  },
```

I want this default (according to the docs) behaviour

```js
      if (cachedResponse) {
        return cachedResponse
      } else {
```

But with different combination of those two rules (including removing  { allowSingleLine: true }) i get either this:

```js
      if (cachedResponse) {
        return cachedResponse
      } 
else {
```

or this: 

```js
      if (cachedResponse) {
        return cachedResponse
      } 
      else {
```

With two options opted in it jumps from correct position to incorrect after each save.

### Reproduction

Can not be run in a online sandbox

### System Info

```Shell
Windows 10, VS Code
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-11-16 15:57
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-11-16 15:57 UTC

**Comment by Dimava** [comment] 2023-11-16 16:51
@altrusl you should disable `eslint.rules.customizations `, type the code as you want to see it, and check what error does it show

It's another rule, possibly one of Antfu's, antfu/if-newlines or whatever

**Comment by altrusl** [comment] 2023-11-16 17:06
> @altrusl you should disable `eslint.rules.customizations `, type the code as you want to see it, and check what error does it show
> 
> It's another rule, possibly one of Antfu's, antfu/if-newlines or whatever

Thank you for the replay
I disabled the customization
The error is: **Closing curly brace appears on the same line as the subsequent block. eslint[style/brace-style]**
I tried to change it and reload vs code window but the rule still applies

```
  stylistic: {
    // "style/brace-style": ["error", "1tbs", { allowSingleLine: true }],
    "style/brace-style": "off",
  },
```

**Comment by altrusl** [comment] 2023-11-16 17:11
Ok, i got it
The line 

```"style/brace-style": ["error", "1tbs", { allowSingleLine: true }],```

must be in the `rules`, not in `stylistic`
That's really not clear...

**Comment by Dimava** [comment] 2023-11-16 17:15
@altrusl did you got caught by #308 ?

**Comment by altrusl** [comment] 2023-11-17 02:38
@Dimava 
Not sure
It looks like "style/brace-style" rules can be applied in the "rules" section, 
and there are no rules "style/brace-style" or "brace-style" in "stylistic" sections
Or at least they don't work

Advice form @antfu from your post to use such construction:
```
  rules: {
    "style/brace-style": "off",
  },
  stylistic: {
    "style/brace-style": ["error", "1tbs", { allowSingleLine: true }],
  },
```
didn't work either

"style/brace-style": ["error", "1tbs", { allowSingleLine: true }], works correctly only in the "rules" section

I can't catch the logic of rule applying

**Comment by Dimava** [comment] 2023-11-17 09:43
@altrusl ESLint has a cmd flag to output parsed config. You may try it to understand the resulting config better, in case you need that

**Comment by Alireza1996Sh** [comment] 2025-07-13 14:48
i had the same issue and i did a change which made error disapper.

```js
stylistic: {
  indent: 2,
  overrides: {
    'sort-keys': ['error', 'asc', { allowLineSeparatedGroups: true }],
    'style/brace-style': ['error', '1tbs', { allowSingleLine: true }],
  },
  quotes: 'single',
  semi: true,
},
```
