### ISSUE TITLE
Parsing error: expected trailing comma in .md file

### ISSUE THREAD

**Issue by BenjaminOddou** [antfu/eslint-config#128] opened 2022-11-12 22:26 UTC
### Describe the bug

Inside a `.md` file I wrote :

```ts
<script setup>
const { data: images } = useFetch<ImageKit[]>('/api/imgkit')
</script>
```

which resulted in :
![eslint bug](https://user-images.githubusercontent.com/85166574/201496850-ae7c9b71-d964-41b3-a102-f6e20dbe1e76.png)

### Reproduction

Please see Screenshot

### System Info

```Shell
------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.19.3`
- Builder:          `vite`
- User Config:      `nitro`, `runtimeConfig`, `modules`, `alias`, `schemaOrg`, `image`, `colorMode`, `pwa`
- Runtime Modules:  `nuxt-windicss@2.5.3`, `@kevinmarrec/nuxt-pwa@0.10.0`, `@nuxt/image-edge@1.0.0-27769790.4b27db3`, `@nuxtjs/color-mode@3.1.8`, `@pinia/nuxt@0.4.3`, `nuxt-schema-org@1.1.0-beta.5`
- Build Modules:    `-`
------------------------------
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ZanMinKian** [comment] 2022-12-15 14:53
Please provide minimal reproducible markdown file.

**Comment by shylockWu** [comment] 2023-03-24 08:17
Hi, I think you might need to add omission of `.md` files in the `.eslintignore` file, like this
```md
*.md
````

**Comment by BenjaminOddou** [comment] 2023-03-24 08:26
hey, @shylockWu, thanks for the feedback, that's  what  I've done already as a workaround 😄

```json
  "ignorePatterns": [
    "tmp/**",
    "README.md"
  ],
```

As a repro @zanminkian :
___
#### Some markdown
```ts
<script setup> // lint error here
const { data: images } = useFetch<ImageKit[]>('/api/imgkit')
</script>
```
___

**Comment by antfu** [comment] 2023-03-24 08:55
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-03-24 08:55 UTC
