### ISSUE TITLE
How can I fix this ESLINT error? I haven't seen any problems.

### ISSUE THREAD

**Issue by fxzer** [antfu/eslint-config#187] opened 2023-05-25 14:48 UTC
### Describe the bug

![image](https://github.com/antfu/eslint-config/assets/68853957/1b6379bf-48a3-42db-b383-bb4a9a2a237a)

![image](https://github.com/antfu/eslint-config/assets/68853957/06c02ec9-f18b-4109-8787-bd69530cd618)

![image](https://github.com/antfu/eslint-config/assets/68853957/e6c03e27-e332-47e0-ab49-40525119d5b4)

## 和Vue官网代码片段一样
<img width="773" alt="image" src="https://github.com/antfu/eslint-config/assets/68853957/cee1982e-e26a-49dd-834f-451773000a00">
### Reproduction

Parsing error: '}' expected.eslint

### System Info

```Shell
"@antfu/eslint-config": "^0.39.3",
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-05-25 16:10
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-05-25 16:10 UTC

**Comment by fxzer** [comment] 2023-05-26 02:28
我找到了问题原因，在上一行不能用 `<string>` 形式类型断言，换成 `as` 就没问题了
![image](https://github.com/antfu/eslint-config/assets/68853957/63f81978-61c5-4816-acbd-3a82d4ef808f)
![image](https://github.com/antfu/eslint-config/assets/68853957/0346b9ff-e27e-4dbe-a74e-408c01269747)

**Comment by so1ve** [comment] 2023-05-27 05:33
It's a volar issue.
