### ISSUE TITLE
cli command(npx @antfu/eslint-config@latest)   execute failed

### ISSUE THREAD

**Issue by fxzer** [antfu/eslint-config#457] opened 2024-04-20 13:47 UTC
### Describe the bug

![image](https://github.com/antfu/eslint-config/assets/68853957/399d3428-4739-4faa-89d0-8b8bb5ab0104)

'Log files:
/Users/fxzer/.npm/_logs/2024-04-20T13_39_36_440Z-debug-0.log

# npm resolution error report

While resolving: undefined@undefined
Found: @antfu/eslint-config@2.12.1
node_modules/@antfu/eslint-config
  @antfu/eslint-config@"2.15.0" from the root project

Could not resolve dependency:
@antfu/eslint-config@"2.15.0" from the root project

Conflicting peer dependency: eslint@9.1.0
node_modules/eslint
  peer eslint@">=9.0.0" from @eslint-react/eslint-plugin@1.5.9
  node_modules/@eslint-react/eslint-plugin
    peerOptional @eslint-react/eslint-plugin@"^1.5.8" from @antfu/eslint-config@2.15.0
    node_modules/@antfu/eslint-config
      @antfu/eslint-config@"2.15.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

# May I ask what the reason is?（请问这是什么原因呢？）

### Reproduction

npx @antfu/eslint-config@latest

### System Info

```Shell
eslint   9.1.0
node    v18.18.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-04-20 14:42
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-20 14:42 UTC

**Comment by thenbe** [comment] 2024-04-20 15:13
@thisIsLoading It probably wasn't your intention, but the sarcasm comes off in bad taste in situations like these.

Anyways, the warning you see can be tracked in https://github.com/typescript-eslint/typescript-eslint/issues/8211

**Comment by TotomInc** [comment] 2024-04-30 08:00
@thisIsLoading use ESLint v8, not v9
