### ISSUE TITLE
0.39.8 deps issue/error

### ISSUE THREAD

**Issue by davidglezz** [antfu/eslint-config#226] opened 2023-07-20 17:53 UTC
### Describe the bug

With 0.39.7 works!
`✖ 70 problems (69 errors, 1 warning)`

With 0.39.8
```
ESLint: 8.45.0

ESLint couldn't find the plugin "eslint-plugin-unused-imports".

(The package "eslint-plugin-unused-imports" was not found when loaded as a Node module from the directory "******".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-unused-imports@latest --save-dev

The plugin "eslint-plugin-unused-imports" was referenced from the config file in ".eslintrc » @antfu/eslint-config » @antfu/eslint-config-vue » @antfu/eslint-config-ts » @antfu/eslint-config-basic".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

### Reproduction

Use 0.39.8

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 858.86 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.05.15.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-07-20 23:12
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-07-20 23:12 UTC
