### ISSUE TITLE
`unocss: true` it's not working

### ISSUE THREAD

**Issue by hooray** [antfu/eslint-config#451] opened 2024-04-15 16:21 UTC
### Describe the bug

use antfu/vitesse and upgrade `@antfu/eslint-config` `@unocss/eslint-config` `eslint` `unocss` to the latest can reproduce

### Reproduction

/

### System Info

```Shell
/
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2024-04-15 16:36
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-04-15 16:36 UTC
