### ISSUE TITLE
eslint-plugin-vitest no working

### ISSUE THREAD

**Issue by chenyulun** [antfu/eslint-config#550] opened 2024-07-19 01:19 UTC
### Describe the bug

`it` is not defined.eslint[no-undef](https://eslint.org/docs/latest/rules/no-undef)
`component.spec.js`
```js
it('test snackbar component plugin', () => {})
```

fix: add `languageOptions.globals`
```js
import vitest from 'eslint-plugin-vitest'
export default antfu({}, [
{
files: ['**/__tests__/**/*.?([cm])[jt]s?(x)'], // or any other pattern
    settings: {
      vitest: {
        typecheck: true,
      },
    },
    languageOptions: {
      globals: {
        ...vitest.environments.env.globals,
      },
    },
    rules: {
      'no-use-before-define': 'off',
    },
}
]

```

### Reproduction

test file + antfu()

### System Info

```Shell
System:
    OS: macOS 12.6.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 77.77 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/Library/Caches/fnm_multishells/91888_1721266798182/bin/node
    Yarn: 1.22.21 - ~/Library/pnpm/yarn
    npm: 9.8.1 - ~/Library/Caches/fnm_multishells/91888_1721266798182/bin/npm
    pnpm: 9.5.0 - ~/Library/pnpm/pnpm
    bun: 1.0.29 - ~/.bun/bin/bun
    Watchman: 2023.10.09.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 126.0.6478.182
    Chrome Canary: 128.0.6602.1
    Edge: 126.0.2592.102
    Safari: 16.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by antfu** [comment] 2024-07-19 08:55
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-07-19 08:55 UTC
