### ISSUE TITLE
Ignores option is not located the first argument

### ISSUE THREAD

**Issue by mutoe** [antfu/eslint-config#374] opened 2023-12-24 05:38 UTC
### Describe the bug

According the README 
https://github.com/antfu/eslint-config/blob/5ea1e2e5271fe1cb5f281c7271b3f4751e26ac33/README.md?plain=1#L61-L67
We support `ignores` options in the first argument when call `antfu({})`. 

But it is not working. When I looked into the source code
https://github.com/antfu/eslint-config/blob/5ea1e2e5271fe1cb5f281c7271b3f4751e26ac33/src/factory.ts#L51-L65

I found that it should in the second parameter. I'm not sure, is this due to a documentation issue or a functional issue?

### Reproduction

N/A. It's a type error, so I can't provide specific unit tests

### System Info

```Shell
N/A
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-12-25 13:40
It's from `FlatConfigItem`, I am sure the types works.

**Comment by antfu** [comment] 2023-12-25 13:40
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-12-25 13:40 UTC
