### ISSUE TITLE
type-aware rule in typescript is not overridden

### ISSUE THREAD

**Issue by ryoppippi** [antfu/eslint-config#584] opened 2024-08-16 15:59 UTC
### Describe the bug

https://github.com/antfu/eslint-config/blob/172f9037cfa6ffae47b1bb5a215091470b09e674/src/configs/typescript.ts#L161
When I add some override config 
![Screenshot 2024-08-16 at 16 57 27](https://github.com/user-attachments/assets/1002e4f5-3519-438a-a0cb-196b66becf70)
for typescript, I found that tsAware config is not overridden (e.x. ts/strict-boolean-expressions).

### Reproduction

no repro

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 119.58 MB / 36.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.15.1 - ~/.local/share/devbox/global/default/.devbox/nix/profile/default/bin/node
    npm: 10.7.0 - ~/.local/share/devbox/global/default/.devbox/nix/profile/default/bin/npm
    pnpm: 9.7.1 - ~/.local/share/devbox/global/default/.devbox/nix/profile/default/bin/pnpm
    bun: 1.1.21 - ~/.local/share/aquaproj-aqua/bin/bun
  Browsers:
    Chrome: 127.0.6533.120
    Safari: 17.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by TotomInc** [comment] 2024-08-19 06:32
Isn't it a duplicate of https://github.com/antfu/eslint-config/issues/521?

**Closed** 2024-08-22 22:03 UTC
