### ISSUE TITLE
vscode error

### ISSUE THREAD

**Issue by senbochen** [antfu/eslint-config#124] opened 2022-10-24 11:57 UTC
### Describe the bug

Referenced from: /Users/mac/Desktop/Kfang/kfang-task-platform/node_modules/@antfu/eslint-config-vue/index.js
    at configMissingError (/Users/mac/Desktop/Kfang/kfang-task-platform/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedPluginConfig (/Users/mac/Desktop/Kfang/kfang-task-platform/node_modules/eslint/lib/cli-engine/config-array-factory.js:792:31)
    at ConfigArrayFactory._loadExtends (/Users/mac/Desktop/Kfang/kfang-task-platform/node_modules/eslint/lib/cli-engine/config-array-factory.js:725:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/mac/Desktop/Kfang/kfang-task-platform/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/mac/Desktop/Kfang/kfang-task-platform/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/mac/Desktop/Kfang/kfang-task-platform/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/mac/Desktop/Kfang/kfang-task-platform/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
[Error - 7:52:04 PM] ESLint stack trace:
[Error - 7:52:04 PM] Error: Failed to load config "plugin:vue/vue3-recommended" to extend from.
Referenced from: /Users/mac/Desktop/Kfang/kfang-task-platform/node_modules/@antfu/eslint-config-vue/index.js

[Error - 7:52:04 PM] ESLint stack trace:
[Error - 7:52:04 PM] Error: Failed to load config "plugin:vue/vue3-recommended" to extend from.
Referenced from: /Users/mac/Desktop/Kfang/kfang-task-platform/node_modules/@antfu/eslint-config-vue/index.js

### Reproduction

solve

### System Info

```Shell
macOs cataLina 10.15.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2022-10-24 11:57
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-10-24 11:57 UTC
